//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDoSomethingRemote")]
public interface IDoSomethingRemote
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoSomethingRemote/GetMessage", ReplyAction="http://tempuri.org/IDoSomethingRemote/GetMessageResponse")]
    string GetMessage(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoSomethingRemote/GetMessage", ReplyAction="http://tempuri.org/IDoSomethingRemote/GetMessageResponse")]
    System.Threading.Tasks.Task<string> GetMessageAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDoSomethingRemoteChannel : IDoSomethingRemote, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DoSomethingRemoteClient : System.ServiceModel.ClientBase<IDoSomethingRemote>, IDoSomethingRemote
{
    
    public DoSomethingRemoteClient()
    {
    }
    
    public DoSomethingRemoteClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DoSomethingRemoteClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DoSomethingRemoteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DoSomethingRemoteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetMessage(string name)
    {
        return base.Channel.GetMessage(name);
    }
    
    public System.Threading.Tasks.Task<string> GetMessageAsync(string name)
    {
        return base.Channel.GetMessageAsync(name);
    }
}
